@startuml "sequence"
Alice -> Bob: test3
Alice --> Bob: test1
@enduml

@startuml "mix"
allowmixing
abstract test
actor Bob #red
@enduml

@startuml "class"
!theme vp from .
scale 2
title "Hello"
top to bottom direction
legend

    This is a legendary legend
end legend


class Entity
class Troop
class Vehicle

class Tank
Vehicle <|-- Tank

allowmixing
class Example
{
    +counter: int
    -test: bool
}

rectangle Stuff {
    class a
    {
        #name: string
    }
}

a -> Example: some stuff happening here

Example -> a
a <- Example : " "
a *.. Example
@enduml

@startuml
listsprite
@enduml