!include <font-awesome/common>
@startuml Rhodey Class Diagram
skinparam classAttributeIconSize 0
title Rhodey War Simulator
hide circle
skinparam linetype ortho

' ===== CLASSES =====

rectangle "AllianceGroups" {
    class Alliance {
        - members: vector<Conglomerate*>
    }

    class AllianceMember {
        name: string
    }
    note bottom #lightgreen : DECORATOR

    class Conglomerate{
        - name: string
        + add(Conglomerate)*: void
        + print(): void
        + ~Conglomerate()
    }

    class Country {
        - sizeOfArmy: int
        - population: int
        - economy: double
        - morale: double
        - resolve: double
        - supplies: double
        - attrition: double
        - forces: Military
        - locations: vector<Location*>
        - Allies: vector<Countries*>
        - trainingFacilitys: vector<TroopFactory*>
        - vehicleFactories: vector<VehicleFactory*>
    }

    class Faction {
        - sizeOfArmy: int
        - population: int
        - economy: int
        - morale: int
        - forces: Military
    }

    class Location {
        - name: string
        - description: string
        - terrain: string
        - population: int
    }
}
note bottom #lightgreen : COMPOSITE



rectangle "War " as War {

    class Simulation {
        + Simulation()
        {static} - uniqueInstance: Simulation*
        # Simulation()
        #~Simulation()
        #Simulation(Simulation &)
        #=(Simulation &) : Simulation &
        - war: War*
        - playerName: string
        ~Simulation()
        
    }
        
    class War{
        - participants: vector<Conglomerate*>
        - reasonForWar: string
        - reasonEndWar: string
        - battles: vector<Battle*>
        - state: WarPhases
        + request(): void
        + setState(phase: WarPhases): void
        + makeMemento():WarMemento
        + restoreBeforeState(WarMemento memento): void
    }



    class WarPhases {
        #war: War*
        {abstract} + handle(): void
        {abstract} + changeState(): void
    }

    class Dispute {
        + handle(): void
        + changeState(): void
    }

    class Conflict {
        + handle(): void
        + changeState(): void
    }

    class Hostilities {
        + handle(): void
        + changeState(): void
    }

    class PostHostilitiesConflict {
        + handle(): void
        + changeState(): void
    }

    class PostHostilitiesDispute {
        + handle(): void
        + changeState(): void
    }

    class DisputeSettled {
        + handle(): void
        + changeState(): void
    }
    note bottom #lightgreen : STATE
}
note top of War #lightgreen : SINGLETON





rectangle Military {
    class Military {
        - BattleGroups: vector<Forces*>
        - Spies: vector<SpyAgency*>
        {abstract} + move(): void
        ~Military()
    }

    class Forces {
        - name: string
        - army: Army*
        - navy: Navy*
        - airforce: Airforce*
        - location: Location*
        {abstract} + move(): void
        ~Military()
    }

    class Army {
        - name: string
        - numSoldiers: int
        - numCommanders: int
        - numTanks: int
        - numTrucks: int
        - units: vector<Entity*>
        + move(): void
        ~Army()
    }

    class Navy {
        - name: string
        - numCargoShips: int
        - numWarShips: int
        - numCarriers: int
        - numSubmarines: int
        - numFighters: int
        - units: vector<Entity*>
        + move(): void
        ~Navy()
    }

    class AirForce {
        - name: string
        - numFighters: int
        - numBombers: int
        - units: vector<Entity*>
        + move(): void
        ~AirForce()
    }

    rectangle Spies {

        class SpyAgency {
            # workFor: vector<Country*>
            # spyingOn: vector<Country*>
            # status: string
            + SpyAgency(spyingFor Country*, spyingOn Country*)
            + update(): void
            ~SpyAgency()
        }

        class Spy {
            {abstract} + update(): void
        }

    }
    note right #lightgreen : OBSERVER
}





'==== Factory method ===='
rectangle "Factories" {
    class UnitFactory{
        # name: string
        # hp: int
        # dmg: int
        + unitFactory()
        ~ unitFactory()
        + {abstract} makeUnit(): Entity*
        
    }

    class VehicleFactory {
        + VehicleFactory()
        ~ VehicleFactory()
        + makeUnit(): Entity*
    }

    class TroopFactory {
        + TroopFactory()
        ~ TruckFactory()
        + makeUnit(): Entity*
    }

    enum VehicleType {
        <<enumeration>>
        Truck
        Tank
        Carrier
        CargoShip
        Warship
        Submarine
        FighterJet
        Bomber
        CargoPlane
    }

    enum TroopType {
        <<enumeration>>
        Soldier
        Commander
        Spy
    }
}
note bottom #lightgreen : ABSTRACT FACTORY

class Battle {
    - country: Country*
    - location: Location*
    - attackingForces: Forces**
    - defendingForces: Forces**
    + Battle(Forces~**, Forces~**, Location*, Country*)
    + start(): void
    + end(): void
    ~Battle()
}


'==== Entities ===='
rectangle "Entities" {
    
    class Entity {
        - name: string
        - hp: int
        - dmg: int
        - weapons: Weapon**
        + Entity()
        {abstract} + attack(): void
        {abstract} + defend(): void
        {abstract} + clone(): Entity
    }
    note bottom #lightgreen : PROTOTYPE

    class Vehicle {
        - capacity: int
        + Vehicle()
        {abstract} + attack(): void
        {abstract} + defend(): void
        {abstract} + clone(): Vehicle
    }

    class GroundVehicle {
        + GroundVehicle()
        {abstract} + attack(): void
        {abstract} + defend(): void
        {abstract} + clone(): GroundVehicle
    }

    class Truck {
        + Truck()
        + attack(): void
        + defend(): void
        + clone(): GroundVehicle
    }

    class Tank {
        + Tank()
        + attack(): void
        + defend(): void
        + clone(): GroundVehicle
    }

    class AirVehicle {
        + AirVehicle()
        {abstract} + attack(): void
        {abstract} + defend(): void
        {abstract} + clone(): AirVehicle
    }

    class FighterJet {
        + FighterJet()
        + attack(): void
        + defend(): void
        + clone(): AirVehicle
    }

    class Bomber {
        + Bomber()
        + attack(): void
        + defend(): void
        + clone(): AirVehicle
    }

    class CargoPlane {
        + CargoPlane()
        + attack(): void
        + defend(): void
        + clone(): AirVehicle
    }

    class WaterVehicle {
        + WaterVehicle()
        {abstract} + attack(): void
        {abstract} + defend(): void
        {abstract} + clone(): WaterVehicle
    }

    class CargoShip {
        + CargoShip()
        + attack(): void
        + defend(): void
        + clone(): WaterVehicle
    }

    class Warship {
        + Warship()
        + attack(): void
        + defend(): void
        + clone(): WaterVehicle
    }

    class Submarine {
        + Submarine()
        + attack(): void
        + defend(): void
        + clone(): WaterVehicle
    }

    class Carrier {
        + Carrier()
        + attack(): void
        + defend(): void
        + clone(): WaterVehicle
    }

    class Troop {
        + Troop()
        {abstract} + attack(): void
        {abstract} + defend(): void
        {abstract} + clone(): Troop
    }

    class Soldier {
        + Soldier()
        + attack(): void
        + defend(): void
        + clone(): Troop
    }

    class Commander {
        + Commander()
        + attack(): void
        + defend(): void
        + command(): void
        + clone(): Troop
    }

    class Weapon {
        - weaponName: string
        - dmg: int
    }
}
note bottom #lightgreen : TEMPLATE METHOD


'==== Different strategy states ===='
rectangle "Strategy States" as StratStates {
    class BattleStrategy {
        + battleAlgorithm()
        {abstract} + redistributeTroops(): void
        {abstract} + recruitTroops(): void
        {abstract} + attack(): void
        {abstract} + defend(): void
        {abstract} + ReasearchAndDevelop(): void
        {abstract} + buildVehicles(): void
        {abstract} + buildWeapons(): void
        {abstract} + makeAlliance(): void
        {abstract} + endAlliance(): void
        {abstract} + surrender(): void
        {abstract} + proposeTreaty(): void
        {abstract} + spy(): void
    }

    class DefensiveStrategy {
        + defensiveAlgorithm()
        + redistributeTroops(): void
        + recruitTroops(): void
        + defend(): void
        + ReasearchAndDevelop(): void
        + buildVehicles(): void
        + buildWeapons(): void
        + makeAlliance(): void
        + endAlliance(): void
        + surrender(): void
        + proposeTreaty(): void
        + spy(): void
    }
    class OffensiveStrategy {
        +offensiveAlgorithm()
        + defensiveAlgorithm()
        + redistributeTroops(): void
        + recruitTroops(): void
        + attack(): void
        + defend(): void
        + ReasearchAndDevelop(): void
        + buildVehicles(): void
        + buildWeapons(): void
        + makeAlliance(): void
        + endAlliance(): void
        + surrender(): void
        + proposeTreaty(): void
        + spy(): void
    }
    
    class ResearchiveStrategy {
        +researchAlgorithm()
        + defensiveAlgorithm()
        + redistributeTroops(): void
        + recruitTroops(): void
        + attack(): void
        + defend(): void
        + ReasearchAndDevelop(): void
        + buildVehicles(): void
        + buildWeapons(): void
        + makeAlliance(): void
        + endAlliance(): void
        + surrender(): void
        + proposeTreaty(): void
        + spy(): void
    }

    class PrepareStrategy {
        +researchAlgorithm()
        + defensiveAlgorithm()
        + redistributeTroops(): void
        + recruitTroops(): void
        + attack(): void
        + defend(): void
        + ReasearchAndDevelop(): void
        + buildVehicles(): void
        + buildWeapons(): void
        + makeAlliance(): void
        + endAlliance(): void
        + surrender(): void
        + proposeTreaty(): void
        + spy(): void
    }
}
note right of StratStates #lightgreen : STRATEGY




'==== Iterators ===='
rectangle "Iterators" as Iterators {
    class normalIterator {
        {abstract} +first()
        {abstract} +next()
        {abstract} +isDone()
        {abstract} +currentItem()
    }
'==== Aliance Groups Iterators ===='
    class allianceIterators {
        +first()
        +next()
        +isDone()
        +currentItem()
    }
    class conglomerateIterator {
        +first()
        +next()
        +isDone()
        +currentItem()
    }
    class countryIterator {
        +first()
        +next()
        +isDone()
        +currentItem()
    }
    class factionIterator {
        +first()
        +next()
        +isDone()
        +currentItem()
    }
}
note bottom of Iterators #lightgreen : ITERATOR

rectangle "Mementos" as Mementos {
    class WarMemento{
        +getState()
        -state: WarState*
        ~Memento():virtual
    }
    class caretaker {
        - warStates: vector<WarMemento>
        + add(memento WarMemento):void

    }

    class WarState { 
        - Vector<String>
        - WarState(War* war)
    }
}
note top of Mementos #lightgreen : MEMENTO

' ===== RELATIONSHIPS =====
Simulation o- War
Simulation o- Simulation

Entity o- Weapon
Entity <|-- Troop
Entity <|-- Vehicle
Troop <|-- Soldier
Troop <|-- Commander
Vehicle <|-- GroundVehicle
Vehicle <|-- AirVehicle
Vehicle <|-- WaterVehicle
GroundVehicle <|-- Truck
GroundVehicle <|-- Tank
AirVehicle <|-- FighterJet
AirVehicle <|-- Bomber
AirVehicle <|-- CargoPlane
WaterVehicle <|-- CargoShip
WaterVehicle <|-- Warship
WaterVehicle <|-- Submarine
WaterVehicle <|-- Carrier

    

VehicleFactory ..> Truck : <<instantiates>>
VehicleFactory ..> Tank : <<instantiates>>
VehicleFactory ..> Warship : <<instantiates>>
VehicleFactory ..> Submarine : <<instantiates>>
VehicleFactory ..> Carrier : <<instantiates>>
VehicleFactory ..> CargoShip : <<instantiates>>
VehicleFactory ..> Bomber : <<instantiates>>
VehicleFactory ..> CargoPlane : <<instantiates>>
TroopFactory   ..> Soldier : <<instantiates>>
TroopFactory   ..> Commander : <<instantiates>>

War ..> WarMemento
caretaker o-- WarMemento
WarMemento o-- WarState

Forces o-- Army
Forces o-- Navy
Forces o-- AirForce
Forces o-- Location

Military o-- Forces

Army o-- Entity
Navy o-- Entity
AirForce o-- Entity

Country o- Location
Country *-- Military
Country o-- VehicleFactory
Country o-- TroopFactory

Battle o-- Country
Battle o-- Forces

SpyAgency <|-- Spy
Military o-- SpyAgency

AllianceMember <|-- Country
AllianceMember <|-- Faction
Conglomerate <|-- Alliance
Conglomerate <|-- AllianceMember
Conglomerate o-- Alliance
BattleStrategy o-- Conglomerate
DefensiveStrategy <|-- BattleStrategy
OffensiveStrategy <|-- BattleStrategy
ResearchiveStrategy <|-- BattleStrategy
PrepareStrategy <|-- BattleStrategy

Dispute <|-- WarPhases
Conflict <|-- WarPhases
Hostilities <|-- WarPhases
PostHostilitiesConflict <|-- WarPhases
PostHostilitiesDispute <|-- WarPhases
DisputeSettled <|-- WarPhases

War o-l- WarPhases
War o-l- Conglomerate
WarPhases o- War
War o-- Battle

'Iterators'
Conglomerate ..> normalIterator : <<creates>>
normalIterator <|-- allianceIterators
normalIterator <|-- countryIterator
normalIterator <|-- factionIterator
normalIterator <|-- conglomerateIterator
Country -- countryIterator
Faction -- factionIterator
Conglomerate -- conglomerateIterator
allianceIterators <.. Alliance : <<instantiate>>

@enduml