@startuml ObjectDiagram

object "Country1:Country" as Country

Country : sizeOfArmy = 10,000
Country : population = 1,200,000
Country : economy = 0.56
Country : morale =0.27
Country : resources = 0.67
Country : research = 0.88
Country : aggresiveness =0.71

object "map1:map" as map
map : numRegions = 10
map : mapWidth = 100
map : mapHeight = 100

Country -->map


object "Region1:Region" as Region1
Region1 : name = "Hanamura"
Region1 : x = 67
Region1 : y=44


map --> Region1

object "Region2:Region" as Region2
Region2 : name = "Eichenwalde"
Region2 : x = 22
Region2 : y=49



map --> Region2

object "Battle1:Battle" as Battle1

object "Battle2:Battle" as Battle2

object "Battle3:Battle" as Battle3

Region1 --> Battle1
Region1 --> Battle2
Region2 --> Battle3







@enduml

